# File : .pep8speaks.yml

message:  # Customize the comment made by the bot
    opened:  # Messages when a new PR is submitted
        header: "Hoi @{name}, thank you for submitting the Pull Request!"
        footer: "Do see the [Hitchhiker's guide to code style](https://goo.gl/hqbW4r)"
    updated:  # Messages when new commits are added to the PR
        header: "Yo @{name}, Thank you for updating!  Let's take another look..."
        footer: ""  # Why to comment the link to the style guide everytime? :)

scanner:
    diff_only: False  # If True, errors caused by only the patch are shown

pycodestyle:
    max-line-length: 120  # Default is 79 in PEP8

no_blank_comment: False  # If True, no comment is made when the bot does not find any pep8 errors
